# Generated by Django 5.2.17 on 2026-09-18 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("training", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Standard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("exercise_max_duration", "удержание, сек"),
                            ("exercise_max_reps", "повторы"),
                            ("exercise_max_weight", "вес"),
                            ("manual", "вручную"),
                        ],
                        default="manual",
                        max_length=24,
                    ),
                ),
                ("target_value", models.DecimalField(decimal_places=2, max_digits=9)),
                ("unit", models.CharField(default="", max_length=16)),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="training.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("period_from", models.DateField()),
                ("period_to", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("correlation", "корреляция"),
                            ("weak_link", "слабое звено"),
                            ("what_worked", "что сработало"),
                            ("forecast", "прогноз"),
                        ],
                        max_length=12,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_to"],
                "indexes": [
                    models.Index(
                        fields=["user", "kind", "period_to"],
                        name="analytics_i_user_id_f3bead_idx",
                    )
                ],
            },
        ),
    ]
