/*
 * Справочник мышц, мышечных групп и упражнений.
 *
 * Роли мышц в упражнении и их вклад в «эффективные подходы»:
 *   p — основная мышца (primary)      × 1.0
 *   s — вспомогательная (secondary)   × 0.5
 *   t — стабилизатор (stabilizer)     × 0.25
 */
(function () {
  'use strict';

  const ROLE_WEIGHT = { p: 1, s: 0.5, t: 0.25 };
  const ROLE_NAME = { p: 'основная', s: 'вспомогательная', t: 'стабилизатор' };

  const GROUPS = [
    { id: 'neck', name: 'Шея' },
    { id: 'traps', name: 'Трапециевидная' },
    { id: 'shoulders', name: 'Дельтовидные' },
    { id: 'rotator', name: 'Вращательная манжета' },
    { id: 'chest', name: 'Грудные' },
    { id: 'back', name: 'Широчайшие и середина спины' },
    { id: 'lowerback', name: 'Поясница' },
    { id: 'biceps', name: 'Сгибатели плеча' },
    { id: 'triceps', name: 'Трицепс' },
    { id: 'forearms', name: 'Предплечья' },
    { id: 'core', name: 'Пресс и кор' },
    { id: 'glutes', name: 'Ягодичные' },
    { id: 'hips', name: 'Сгибатели и приводящие бедра' },
    { id: 'quads', name: 'Квадрицепс' },
    { id: 'hamstrings', name: 'Задняя поверхность бедра' },
    { id: 'calves', name: 'Голень' },
  ];

  const MUSCLES = {
    'sternocleidomastoid': { name: 'Грудино-ключично-сосцевидная', latin: 'm. sternocleidomastoideus', group: 'neck',
      fn: 'Сгибание и поворот головы, наклон шеи в сторону.' },

    'trap-upper': { name: 'Трапеция, верхняя часть', latin: 'm. trapezius, pars descendens', group: 'traps',
      fn: 'Поднимание лопаток (шраги), разгибание и наклон шеи.' },
    'trap-middle': { name: 'Трапеция, средняя часть', latin: 'm. trapezius, pars transversa', group: 'traps',
      fn: 'Сведение лопаток (ретракция), стабилизация лопатки.' },
    'trap-lower': { name: 'Трапеция, нижняя часть', latin: 'm. trapezius, pars ascendens', group: 'traps',
      fn: 'Опускание лопаток, вращение лопатки вверх при подъёме рук.' },

    'delt-front': { name: 'Передняя дельта', latin: 'm. deltoideus, pars clavicularis', group: 'shoulders',
      fn: 'Сгибание плеча (подъём руки вперёд), внутренняя ротация, горизонтальное приведение.' },
    'delt-side': { name: 'Средняя дельта', latin: 'm. deltoideus, pars acromialis', group: 'shoulders',
      fn: 'Отведение плеча (подъём руки в сторону).' },
    'delt-rear': { name: 'Задняя дельта', latin: 'm. deltoideus, pars spinalis', group: 'shoulders',
      fn: 'Разгибание плеча, горизонтальное отведение, наружная ротация.' },

    'infraspinatus': { name: 'Подостная', latin: 'm. infraspinatus', group: 'rotator',
      fn: 'Наружная ротация плеча, стабилизация головки плечевой кости.' },
    'teres-minor': { name: 'Малая круглая', latin: 'm. teres minor', group: 'rotator',
      fn: 'Наружная ротация и приведение плеча, стабилизация сустава.' },

    'pec-upper': { name: 'Большая грудная, ключичная часть', latin: 'm. pectoralis major, pars clavicularis', group: 'chest',
      fn: 'Сгибание плеча и горизонтальное приведение под углом вверх (жим на наклонной).' },
    'pec-mid': { name: 'Большая грудная, грудинная часть', latin: 'm. pectoralis major, pars sternocostalis', group: 'chest',
      fn: 'Горизонтальное приведение плеча, внутренняя ротация.' },
    'pec-lower': { name: 'Большая грудная, брюшная часть', latin: 'm. pectoralis major, pars abdominalis', group: 'chest',
      fn: 'Приведение и разгибание плеча сверху вниз (отжимания на брусьях, жим с отрицательным наклоном).' },

    'lats': { name: 'Широчайшая мышца спины', latin: 'm. latissimus dorsi', group: 'back',
      fn: 'Приведение и разгибание плеча, внутренняя ротация (подтягивания, тяги).' },
    'teres-major': { name: 'Большая круглая', latin: 'm. teres major', group: 'back',
      fn: 'Приведение, разгибание и внутренняя ротация плеча — «помощник» широчайшей.' },
    'rhomboids': { name: 'Ромбовидные', latin: 'mm. rhomboidei major et minor', group: 'back',
      fn: 'Сведение и поднимание лопаток, прижимание лопатки к грудной клетке.' },

    'erectors': { name: 'Разгибатели позвоночника', latin: 'm. erector spinae', group: 'lowerback',
      fn: 'Разгибание и стабилизация позвоночника, удержание нейтральной спины.' },

    'biceps': { name: 'Двуглавая мышца плеча (бицепс)', latin: 'm. biceps brachii', group: 'biceps',
      fn: 'Сгибание локтя, супинация предплечья, сгибание плеча.' },
    'brachialis': { name: 'Плечевая', latin: 'm. brachialis', group: 'biceps',
      fn: 'Сгибание локтя в любом положении кисти — главный сгибатель локтя.' },

    'triceps-long': { name: 'Трицепс, длинная головка', latin: 'm. triceps brachii, caput longum', group: 'triceps',
      fn: 'Разгибание локтя и разгибание плеча; максимально растянута при руке над головой.' },
    'triceps-lateral': { name: 'Трицепс, латеральная головка', latin: 'm. triceps brachii, caput laterale', group: 'triceps',
      fn: 'Мощное разгибание локтя (жимы, разгибания на блоке).' },
    'triceps-medial': { name: 'Трицепс, медиальная головка', latin: 'm. triceps brachii, caput mediale', group: 'triceps',
      fn: 'Разгибание локтя во всех положениях, особенно в конечной фазе.' },

    'brachioradialis': { name: 'Плечелучевая', latin: 'm. brachioradialis', group: 'forearms',
      fn: 'Сгибание локтя в нейтральном хвате (молотки, обратные сгибания).' },
    'forearm-flexors': { name: 'Сгибатели запястья и пальцев', latin: 'mm. flexores carpi et digitorum', group: 'forearms',
      fn: 'Сгибание кисти и пальцев, сила хвата.' },
    'forearm-extensors': { name: 'Разгибатели запястья и пальцев', latin: 'mm. extensores carpi et digitorum', group: 'forearms',
      fn: 'Разгибание кисти и пальцев, стабилизация запястья.' },

    'rectus-abdominis': { name: 'Прямая мышца живота', latin: 'm. rectus abdominis', group: 'core',
      fn: 'Сгибание туловища, подкручивание таза, стабилизация корпуса.' },
    'obliques': { name: 'Наружная косая мышца живота', latin: 'm. obliquus externus abdominis', group: 'core',
      fn: 'Повороты и боковые наклоны туловища, антиротационная стабилизация.' },
    'serratus': { name: 'Передняя зубчатая', latin: 'm. serratus anterior', group: 'core',
      fn: 'Протракция и вращение лопатки вверх, прижатие лопатки к рёбрам.' },

    'glute-max': { name: 'Большая ягодичная', latin: 'm. gluteus maximus', group: 'glutes',
      fn: 'Разгибание и наружная ротация бедра (приседания, тяги, ягодичный мост).' },
    'glute-med': { name: 'Средняя ягодичная', latin: 'm. gluteus medius', group: 'glutes',
      fn: 'Отведение бедра, стабилизация таза при ходьбе и на одной ноге.' },
    'tfl': { name: 'Напрягатель широкой фасции', latin: 'm. tensor fasciae latae', group: 'glutes',
      fn: 'Отведение, сгибание и внутренняя ротация бедра, натяжение подвздошно-большеберцового тракта.' },

    'iliopsoas': { name: 'Подвздошно-поясничная', latin: 'm. iliopsoas', group: 'hips',
      fn: 'Главный сгибатель бедра (подъём коленей, подъёмы ног).' },
    'adductors': { name: 'Приводящие мышцы бедра', latin: 'mm. adductores longus et brevis, m. pectineus, m. gracilis', group: 'hips',
      fn: 'Приведение бедра, стабилизация таза.' },
    'adductor-magnus': { name: 'Большая приводящая', latin: 'm. adductor magnus', group: 'hips',
      fn: 'Приведение и разгибание бедра — активно работает в глубоком приседе и тягах.' },
    'sartorius': { name: 'Портняжная', latin: 'm. sartorius', group: 'hips',
      fn: 'Сгибание бедра и голени, наружная ротация бедра.' },

    'rectus-femoris': { name: 'Прямая мышца бедра', latin: 'm. rectus femoris', group: 'quads',
      fn: 'Разгибание колена и сгибание бедра (двусуставная).' },
    'vastus-lateralis': { name: 'Латеральная широкая', latin: 'm. vastus lateralis', group: 'quads',
      fn: 'Разгибание колена; формирует внешний контур бедра.' },
    'vastus-medialis': { name: 'Медиальная широкая («капля»)', latin: 'm. vastus medialis', group: 'quads',
      fn: 'Разгибание колена, стабилизация надколенника.' },

    'biceps-femoris': { name: 'Двуглавая мышца бедра', latin: 'm. biceps femoris', group: 'hamstrings',
      fn: 'Сгибание колена, разгибание бедра, наружная ротация голени.' },
    'semitendinosus': { name: 'Полусухожильная', latin: 'm. semitendinosus', group: 'hamstrings',
      fn: 'Сгибание колена, разгибание бедра, внутренняя ротация голени.' },
    'semimembranosus': { name: 'Полуперепончатая', latin: 'm. semimembranosus', group: 'hamstrings',
      fn: 'Сгибание колена, разгибание бедра, стабилизация коленного сустава.' },

    'gastrocnemius': { name: 'Икроножная', latin: 'm. gastrocnemius', group: 'calves',
      fn: 'Подошвенное сгибание стопы (подъём на носки) при прямом колене, сгибание колена.' },
    'soleus': { name: 'Камбаловидная', latin: 'm. soleus', group: 'calves',
      fn: 'Подошвенное сгибание стопы, особенно при согнутом колене.' },
    'tibialis': { name: 'Передняя большеберцовая', latin: 'm. tibialis anterior', group: 'calves',
      fn: 'Тыльное сгибание (подъём носка) и супинация стопы.' },
    'peroneus': { name: 'Малоберцовые', latin: 'mm. fibulares (peronei)', group: 'calves',
      fn: 'Пронация (эверсия) и подошвенное сгибание стопы, стабилизация голеностопа.' },
  };

  const HAMS = ['biceps-femoris', 'semitendinosus', 'semimembranosus'];
  const QUADS_V = ['vastus-lateralis', 'vastus-medialis'];
  const TRI = ['triceps-lateral', 'triceps-medial'];

  // cat — категория для фильтра библиотеки (id группы)
  const EXERCISES = [
    // ---- Грудь
    { id: 'bench', name: 'Жим штанги лёжа', cat: 'chest',
      p: ['pec-mid', 'pec-lower'], s: ['pec-upper', 'delt-front', ...TRI], t: ['triceps-long', 'serratus', 'lats'] },
    { id: 'incline-bench', name: 'Жим на наклонной скамье', cat: 'chest',
      p: ['pec-upper'], s: ['pec-mid', 'delt-front', ...TRI], t: ['triceps-long', 'serratus'] },
    { id: 'decline-bench', name: 'Жим на скамье с отрицательным наклоном', cat: 'chest',
      p: ['pec-lower', 'pec-mid'], s: TRI, t: ['delt-front', 'triceps-long'] },
    { id: 'db-press', name: 'Жим гантелей лёжа', cat: 'chest',
      p: ['pec-mid', 'pec-lower'], s: ['pec-upper', 'delt-front', ...TRI], t: ['serratus', 'biceps'] },
    { id: 'dips', name: 'Отжимания на брусьях (грудной стиль)', cat: 'chest',
      p: ['pec-lower', ...TRI], s: ['pec-mid', 'delt-front', 'triceps-long'], t: ['serratus', 'trap-lower', 'rhomboids'] },
    { id: 'pushups', name: 'Отжимания от пола', cat: 'chest',
      p: ['pec-mid'], s: ['pec-upper', 'pec-lower', 'delt-front', ...TRI], t: ['rectus-abdominis', 'obliques', 'serratus'] },
    { id: 'cable-fly', name: 'Сведение рук в кроссовере', cat: 'chest',
      p: ['pec-mid', 'pec-lower'], s: ['pec-upper', 'delt-front'], t: ['biceps', 'serratus'] },
    { id: 'pec-deck', name: 'Бабочка (пек-дек)', cat: 'chest',
      p: ['pec-mid'], s: ['pec-upper', 'pec-lower'], t: ['delt-front'] },
    { id: 'pullover', name: 'Пуловер с гантелью', cat: 'chest',
      p: ['lats', 'pec-lower'], s: ['triceps-long', 'teres-major', 'serratus'], t: ['pec-mid', 'rectus-abdominis'] },

    // ---- Спина
    { id: 'pullups', name: 'Подтягивания широким хватом', cat: 'back',
      p: ['lats', 'teres-major'], s: ['biceps', 'brachialis', 'brachioradialis', 'rhomboids', 'trap-lower', 'delt-rear'],
      t: ['forearm-flexors', 'rectus-abdominis', 'infraspinatus', 'teres-minor'] },
    { id: 'chinups', name: 'Подтягивания обратным хватом', cat: 'back',
      p: ['lats', 'biceps'], s: ['brachialis', 'teres-major', 'pec-lower', 'rhomboids'], t: ['forearm-flexors', 'trap-lower', 'rectus-abdominis'] },
    { id: 'lat-pulldown', name: 'Тяга верхнего блока', cat: 'back',
      p: ['lats'], s: ['teres-major', 'biceps', 'brachialis', 'rhomboids', 'trap-lower'], t: ['delt-rear', 'forearm-flexors'] },
    { id: 'barbell-row', name: 'Тяга штанги в наклоне', cat: 'back',
      p: ['lats', 'rhomboids', 'trap-middle'], s: ['delt-rear', 'teres-major', 'biceps', 'brachialis', 'erectors', 'infraspinatus'],
      t: [...HAMS, 'glute-max', 'forearm-flexors', 'brachioradialis'] },
    { id: 'db-row', name: 'Тяга гантели одной рукой', cat: 'back',
      p: ['lats', 'rhomboids'], s: ['trap-middle', 'delt-rear', 'teres-major', 'biceps', 'brachialis'], t: ['obliques', 'erectors', 'forearm-flexors'] },
    { id: 'cable-row', name: 'Тяга горизонтального блока', cat: 'back',
      p: ['rhomboids', 'trap-middle', 'lats'], s: ['delt-rear', 'biceps', 'brachialis', 'teres-major', 'trap-lower'], t: ['erectors', 'forearm-flexors'] },
    { id: 'face-pull', name: 'Тяга каната к лицу (face pull)', cat: 'shoulders',
      p: ['delt-rear', 'infraspinatus', 'teres-minor'], s: ['trap-middle', 'rhomboids', 'trap-lower'], t: ['biceps', 'forearm-extensors'] },
    { id: 'shrugs', name: 'Шраги со штангой', cat: 'traps',
      p: ['trap-upper'], s: ['trap-middle'], t: ['forearm-flexors', 'brachioradialis', 'rhomboids'] },
    { id: 'deadlift', name: 'Становая тяга', cat: 'lowerback',
      p: ['glute-max', 'erectors', ...HAMS, 'adductor-magnus'],
      s: [...QUADS_V, 'trap-upper', 'trap-middle', 'lats', 'forearm-flexors'],
      t: ['rectus-femoris', 'rectus-abdominis', 'obliques', 'rhomboids', 'brachioradialis', 'gastrocnemius', 'soleus'] },
    { id: 'hyperext', name: 'Гиперэкстензия', cat: 'lowerback',
      p: ['erectors'], s: ['glute-max', ...HAMS], t: ['adductor-magnus'] },
    { id: 'good-morning', name: 'Наклоны со штангой (гуд морнинг)', cat: 'lowerback',
      p: ['erectors', ...HAMS], s: ['glute-max', 'adductor-magnus'], t: ['rectus-abdominis', 'obliques', 'trap-middle'] },

    // ---- Плечи
    { id: 'ohp', name: 'Армейский жим стоя', cat: 'shoulders',
      p: ['delt-front'], s: ['delt-side', ...TRI, 'triceps-long', 'pec-upper', 'trap-upper', 'serratus'],
      t: ['rectus-abdominis', 'obliques', 'erectors', 'glute-max', 'trap-lower'] },
    { id: 'db-shoulder-press', name: 'Жим гантелей сидя', cat: 'shoulders',
      p: ['delt-front'], s: ['delt-side', ...TRI, 'pec-upper'], t: ['triceps-long', 'trap-upper', 'serratus'] },
    { id: 'lateral-raise', name: 'Махи гантелями в стороны', cat: 'shoulders',
      p: ['delt-side'], s: ['delt-front', 'trap-upper'], t: ['delt-rear', 'serratus', 'forearm-extensors'] },
    { id: 'front-raise', name: 'Подъём гантелей перед собой', cat: 'shoulders',
      p: ['delt-front'], s: ['pec-upper', 'delt-side'], t: ['serratus', 'trap-upper'] },
    { id: 'reverse-fly', name: 'Разведение гантелей в наклоне', cat: 'shoulders',
      p: ['delt-rear'], s: ['infraspinatus', 'teres-minor', 'trap-middle', 'rhomboids'], t: ['delt-side', 'erectors'] },
    { id: 'upright-row', name: 'Тяга штанги к подбородку', cat: 'shoulders',
      p: ['delt-side', 'trap-upper'], s: ['delt-front', 'biceps', 'brachialis', 'brachioradialis'], t: ['forearm-flexors', 'trap-middle'] },
    { id: 'y-raise', name: 'Y-подъёмы лёжа на наклонной', cat: 'traps',
      p: ['trap-lower'], s: ['trap-middle', 'delt-side', 'delt-rear'], t: ['infraspinatus', 'teres-minor', 'serratus'] },
    { id: 'ext-rotation', name: 'Наружная ротация плеча на блоке', cat: 'rotator',
      p: ['infraspinatus', 'teres-minor'], s: ['delt-rear'], t: ['trap-middle', 'rhomboids'] },

    // ---- Руки
    { id: 'barbell-curl', name: 'Подъём штанги на бицепс', cat: 'biceps',
      p: ['biceps'], s: ['brachialis', 'brachioradialis'], t: ['delt-front', 'forearm-flexors'] },
    { id: 'hammer-curl', name: 'Молотки с гантелями', cat: 'biceps',
      p: ['brachialis', 'brachioradialis'], s: ['biceps'], t: ['forearm-extensors', 'forearm-flexors'] },
    { id: 'preacher-curl', name: 'Сгибания на скамье Скотта', cat: 'biceps',
      p: ['biceps', 'brachialis'], s: ['brachioradialis'], t: ['forearm-flexors'] },
    { id: 'concentration-curl', name: 'Концентрированные сгибания', cat: 'biceps',
      p: ['biceps'], s: ['brachialis'], t: ['brachioradialis'] },
    { id: 'close-grip-bench', name: 'Жим лёжа узким хватом', cat: 'triceps',
      p: TRI, s: ['triceps-long', 'pec-mid', 'pec-lower', 'delt-front'], t: ['pec-upper', 'serratus'] },
    { id: 'skull-crusher', name: 'Французский жим лёжа', cat: 'triceps',
      p: ['triceps-long', 'triceps-medial'], s: ['triceps-lateral'], t: ['forearm-flexors', 'lats'] },
    { id: 'pushdown', name: 'Разгибания рук на блоке', cat: 'triceps',
      p: TRI, s: ['triceps-long'], t: ['forearm-extensors', 'rectus-abdominis'] },
    { id: 'overhead-ext', name: 'Разгибание руки из-за головы', cat: 'triceps',
      p: ['triceps-long'], s: TRI, t: ['rectus-abdominis', 'serratus'] },
    { id: 'bench-dips', name: 'Обратные отжимания от скамьи', cat: 'triceps',
      p: TRI, s: ['triceps-long', 'delt-front', 'pec-lower'], t: ['rhomboids'] },
    { id: 'wrist-curl', name: 'Сгибания запястий', cat: 'forearms',
      p: ['forearm-flexors'], s: [], t: ['brachioradialis'] },
    { id: 'reverse-wrist-curl', name: 'Разгибания запястий', cat: 'forearms',
      p: ['forearm-extensors'], s: ['brachioradialis'], t: [] },
    { id: 'reverse-curl', name: 'Сгибания обратным хватом', cat: 'forearms',
      p: ['brachioradialis', 'brachialis'], s: ['forearm-extensors', 'biceps'], t: [] },
    { id: 'farmers-walk', name: 'Прогулка фермера', cat: 'forearms',
      p: ['forearm-flexors', 'trap-upper'], s: ['trap-middle', 'obliques', 'erectors', 'brachioradialis', 'forearm-extensors'],
      t: ['glute-med', 'gastrocnemius', 'soleus', 'rectus-abdominis', 'vastus-lateralis'] },

    // ---- Кор
    { id: 'scap-pushup', name: 'Отжимания с протракцией лопаток', cat: 'core',
      p: ['serratus'], s: ['pec-mid', 'delt-front'], t: ['rectus-abdominis', 'obliques', ...TRI] },
    { id: 'crunch', name: 'Скручивания', cat: 'core',
      p: ['rectus-abdominis'], s: ['obliques'], t: [] },
    { id: 'hanging-leg-raise', name: 'Подъём ног в висе', cat: 'core',
      p: ['rectus-abdominis', 'iliopsoas'], s: ['obliques', 'rectus-femoris', 'tfl'], t: ['forearm-flexors', 'lats', 'sartorius'] },
    { id: 'lying-leg-raise', name: 'Подъём ног лёжа', cat: 'hips',
      p: ['iliopsoas', 'rectus-abdominis'], s: ['rectus-femoris', 'sartorius'], t: ['obliques', 'tfl'] },
    { id: 'plank', name: 'Планка', cat: 'core',
      p: ['rectus-abdominis'], s: ['obliques', 'serratus', 'delt-front'], t: ['erectors', 'glute-max', 'rectus-femoris', 'pec-mid'] },
    { id: 'side-plank', name: 'Боковая планка', cat: 'core',
      p: ['obliques'], s: ['glute-med', 'rectus-abdominis'], t: ['delt-side', 'tfl', 'erectors'] },
    { id: 'russian-twist', name: 'Русские скручивания', cat: 'core',
      p: ['obliques'], s: ['rectus-abdominis'], t: ['iliopsoas'] },
    { id: 'ab-wheel', name: 'Ролик для пресса', cat: 'core',
      p: ['rectus-abdominis'], s: ['obliques', 'lats', 'serratus'], t: ['delt-front', 'triceps-long', 'iliopsoas', 'rectus-femoris'] },
    { id: 'woodchop', name: 'Дровосек на блоке', cat: 'core',
      p: ['obliques'], s: ['rectus-abdominis', 'serratus'], t: ['delt-front', 'glute-med'] },
    { id: 'neck-flexion', name: 'Сгибание шеи с отягощением', cat: 'neck',
      p: ['sternocleidomastoid'], s: [], t: ['trap-upper'] },
    { id: 'neck-extension', name: 'Разгибание шеи с отягощением', cat: 'neck',
      p: ['trap-upper'], s: ['sternocleidomastoid'], t: [] },

    // ---- Ноги
    { id: 'squat', name: 'Приседания со штангой', cat: 'quads',
      p: [...QUADS_V, 'glute-max', 'adductor-magnus'], s: ['rectus-femoris', 'adductors', 'erectors'],
      t: [...HAMS, 'soleus', 'gastrocnemius', 'rectus-abdominis', 'obliques'] },
    { id: 'front-squat', name: 'Фронтальные приседания', cat: 'quads',
      p: [...QUADS_V, 'rectus-femoris'], s: ['glute-max', 'adductor-magnus', 'erectors', 'rectus-abdominis'],
      t: ['trap-upper', 'trap-middle', 'obliques', 'soleus'] },
    { id: 'leg-press', name: 'Жим ногами', cat: 'quads',
      p: [...QUADS_V, 'glute-max'], s: ['rectus-femoris', 'adductor-magnus', 'adductors'], t: ['biceps-femoris', 'gastrocnemius'] },
    { id: 'lunges', name: 'Выпады с гантелями', cat: 'quads',
      p: [...QUADS_V, 'glute-max'], s: ['rectus-femoris', 'adductor-magnus', 'glute-med'], t: ['obliques', 'gastrocnemius', 'soleus', 'tfl', 'adductors', 'forearm-flexors'] },
    { id: 'bulgarian', name: 'Болгарские сплит-приседания', cat: 'quads',
      p: [...QUADS_V, 'glute-max'], s: ['rectus-femoris', 'glute-med', 'adductor-magnus'], t: ['tfl', 'soleus', 'obliques', 'iliopsoas'] },
    { id: 'leg-extension', name: 'Разгибание ног в тренажёре', cat: 'quads',
      p: ['rectus-femoris', ...QUADS_V], s: [], t: [] },
    { id: 'rdl', name: 'Румынская тяга', cat: 'hamstrings',
      p: [...HAMS, 'glute-max'], s: ['erectors', 'adductor-magnus'], t: ['forearm-flexors', 'trap-upper', 'lats', 'trap-middle'] },
    { id: 'leg-curl', name: 'Сгибание ног лёжа', cat: 'hamstrings',
      p: HAMS, s: ['gastrocnemius'], t: ['sartorius'] },
    { id: 'seated-leg-curl', name: 'Сгибание ног сидя', cat: 'hamstrings',
      p: HAMS, s: [], t: ['gastrocnemius', 'sartorius'] },
    { id: 'nordic', name: 'Нордические сгибания', cat: 'hamstrings',
      p: HAMS, s: ['gastrocnemius'], t: ['glute-max', 'erectors'] },
    { id: 'hip-thrust', name: 'Ягодичный мост со штангой', cat: 'glutes',
      p: ['glute-max'], s: [...HAMS, 'adductor-magnus', 'glute-med'], t: [...QUADS_V, 'rectus-abdominis', 'erectors'] },
    { id: 'kb-swing', name: 'Махи гирей', cat: 'glutes',
      p: ['glute-max', ...HAMS], s: ['erectors', 'delt-front', 'adductor-magnus'], t: ['forearm-flexors', 'trap-upper', 'obliques', 'vastus-lateralis'] },
    { id: 'hip-abduction', name: 'Отведение бедра в тренажёре', cat: 'glutes',
      p: ['glute-med', 'tfl'], s: ['glute-max'], t: [] },
    { id: 'cable-hip-flexion', name: 'Сгибание бедра на нижнем блоке', cat: 'hips',
      p: ['iliopsoas'], s: ['rectus-femoris', 'sartorius', 'tfl'], t: ['rectus-abdominis', 'glute-med'] },
    { id: 'hip-adduction', name: 'Сведение ног в тренажёре', cat: 'hips',
      p: ['adductors', 'adductor-magnus'], s: [], t: ['sartorius'] },
    { id: 'calf-raise', name: 'Подъём на носки стоя', cat: 'calves',
      p: ['gastrocnemius'], s: ['soleus'], t: ['peroneus', 'tibialis'] },
    { id: 'seated-calf', name: 'Подъём на носки сидя', cat: 'calves',
      p: ['soleus'], s: ['gastrocnemius'], t: ['peroneus'] },
    { id: 'tibialis-raise', name: 'Подъём носков (тибиалис)', cat: 'calves',
      p: ['tibialis'], s: [], t: ['peroneus'] },
    { id: 'ankle-eversion', name: 'Отведение стопы с резиной (эверсия)', cat: 'calves',
      p: ['peroneus'], s: [], t: ['tibialis'] },
  ];

  const PRESETS = [
    { id: 'fullbody', name: 'Фулбоди', items: [['squat', 4], ['bench', 4], ['barbell-row', 4], ['ohp', 3], ['rdl', 3], ['plank', 3]] },
    { id: 'push', name: 'Жим (Push)', items: [['bench', 4], ['incline-bench', 3], ['ohp', 3], ['lateral-raise', 4], ['pushdown', 3], ['overhead-ext', 3]] },
    { id: 'pull', name: 'Тяга (Pull)', items: [['deadlift', 3], ['pullups', 4], ['barbell-row', 4], ['face-pull', 3], ['barbell-curl', 3], ['hammer-curl', 3]] },
    { id: 'legs', name: 'Ноги (Legs)', items: [['squat', 4], ['rdl', 3], ['leg-press', 3], ['leg-curl', 3], ['leg-extension', 3], ['calf-raise', 4]] },
    { id: 'upper', name: 'Верх', items: [['bench', 4], ['pullups', 4], ['db-shoulder-press', 3], ['cable-row', 3], ['barbell-curl', 2], ['pushdown', 2]] },
    { id: 'lower', name: 'Низ', items: [['squat', 4], ['rdl', 3], ['bulgarian', 3], ['hip-thrust', 3], ['seated-calf', 3], ['hanging-leg-raise', 3]] },
    { id: 'core', name: 'Кор', items: [['hanging-leg-raise', 3], ['ab-wheel', 3], ['side-plank', 3], ['woodchop', 3], ['hyperext', 3]] },
    { id: 'week-ul', name: 'Неделя: верх/низ ×2', scale: 'week', items: [
      ['bench', 8], ['pullups', 8], ['db-shoulder-press', 6], ['cable-row', 6], ['barbell-curl', 4], ['pushdown', 4], ['lateral-raise', 6], ['face-pull', 4],
      ['squat', 8], ['rdl', 6], ['bulgarian', 6], ['hip-thrust', 6], ['calf-raise', 6], ['hanging-leg-raise', 6]] },
  ];

  // Шкалы: пороги в эффективных подходах [начало «средней», начало «высокой»]
  const SCALES = {
    session: { name: 'Тренировка', t1: 3, t2: 6 },
    week: { name: 'Неделя', t1: 6, t2: 12 },
  };

  window.MUSCLE_DATA = { ROLE_WEIGHT, ROLE_NAME, GROUPS, MUSCLES, EXERCISES, PRESETS, SCALES };
})();
