# Generated by Django 5.2.17 on 2026-09-18 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("training", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Injury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "side",
                    models.CharField(
                        choices=[
                            ("left", "левая"),
                            ("right", "правая"),
                            ("both", "обе"),
                            ("na", "не применимо"),
                        ],
                        default="na",
                        max_length=6,
                    ),
                ),
                (
                    "character",
                    models.CharField(
                        choices=[
                            ("sharp", "острая"),
                            ("dull", "тупая"),
                            ("ache", "ноющая"),
                            ("numbness", "онемение"),
                            ("stiffness", "скованность"),
                            ("other", "другое"),
                        ],
                        default="ache",
                        max_length=12,
                    ),
                ),
                ("started_on", models.DateField()),
                ("resolved_on", models.DateField(blank=True, null=True)),
                ("initial_severity", models.PositiveSmallIntegerField(default=5)),
                ("notes", models.TextField(blank=True)),
                (
                    "body_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="injuries",
                        to="catalog.bodypart",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_on"],
            },
        ),
        migrations.CreateModel(
            name="InjuryExerciseFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("caution", "осторожно"),
                            ("avoid", "лучше исключить"),
                        ],
                        default="caution",
                        max_length=8,
                    ),
                ),
                ("is_auto", models.BooleanField(default=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="injury_flags",
                        to="training.exercise",
                    ),
                ),
                (
                    "injury",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_flags",
                        to="safety.injury",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InjuryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("severity_1_10", models.PositiveSmallIntegerField()),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "injury",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="safety.injury",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="RecurrenceNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("days_between", models.PositiveSmallIntegerField()),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "body_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.bodypart",
                    ),
                ),
                (
                    "first_injury",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="safety.injury",
                    ),
                ),
                (
                    "second_injury",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence_notices",
                        to="safety.injury",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("date", models.DateField()),
                ("pain_without_weight", models.BooleanField()),
                ("answer_note", models.CharField(blank=True, max_length=200)),
                ("unlocked", models.BooleanField(default=False)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_tests",
                        to="training.exercise",
                    ),
                ),
                (
                    "injury",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_tests",
                        to="safety.injury",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="WeightLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("max_weight_kg", models.DecimalField(decimal_places=2, max_digits=6)),
                ("reason", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_limits",
                        to="training.exercise",
                    ),
                ),
                (
                    "movement_tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.movementtag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeightLimitOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "entered_weight_kg",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "limit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="safety.weightlimit",
                    ),
                ),
                (
                    "set_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="training.setlog",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="injury",
            index=models.Index(
                fields=["user", "body_part", "started_on"],
                name="safety_inju_user_id_a074e0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="injuryexerciseflag",
            constraint=models.UniqueConstraint(
                fields=("injury", "exercise"), name="injury_exercise_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="injurylog",
            constraint=models.UniqueConstraint(
                fields=("injury", "date"), name="injury_log_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="recurrencenotice",
            constraint=models.UniqueConstraint(
                fields=("user", "second_injury"), name="recurrence_notice_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="weightlimit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("exercise__isnull", False),
                    ("movement_tag__isnull", False),
                    _connector="OR",
                ),
                name="weight_limit_target_required",
            ),
        ),
    ]
