# Generated by Django 5.2.17 on 2026-09-18 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("title", models.CharField(max_length=120)),
                ("target_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(default="count", max_length=16)),
                ("started_on", models.DateField()),
                ("deadline", models.DateField(blank=True, null=True)),
                ("auto_rule", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_on"],
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "kind",
                    models.CharField(
                        choices=[("quit", "отказ"), ("build", "полезная")],
                        default="quit",
                        max_length=6,
                    ),
                ),
                (
                    "decision_date",
                    models.DateField(
                        help_text="Дата решения. Никогда не сбрасывается."
                    ),
                ),
                ("timeline_kind", models.SlugField(blank=True, max_length=40)),
                ("unit", models.CharField(default="days", max_length=10)),
                (
                    "target_per_week",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "money_per_day",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("icon_token", models.CharField(blank=True, max_length=40)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Replacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("text", models.CharField(max_length=160)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replacements",
                        to="habits.habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SosSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("passed", "прошло"),
                            ("gave_in", "не удержался"),
                            ("unknown", "неизвестно"),
                        ],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sos_sessions",
                        to="habits.habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ChallengeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("client_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("source", models.CharField(default="manual", max_length=10)),
                ("external_id", models.CharField(blank=True, max_length=128)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="habits.challenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "client_id"),
                        name="habits_challengeentry_client_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CravingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("client_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("intensity_1_10", models.PositiveSmallIntegerField()),
                ("place", models.CharField(blank=True, max_length=80)),
                ("what_helped", models.CharField(blank=True, max_length=200)),
                ("resisted", models.BooleanField(default=True)),
                (
                    "trigger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.cravingtrigger",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cravings",
                        to="habits.habit",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "client_id"),
                        name="habits_cravinglog_client_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HabitCheckin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("client_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("date", models.DateField(db_index=True)),
                ("done", models.BooleanField(default=True)),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="habits.habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "client_id"),
                        name="habits_habitcheckin_client_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("habit", "date"), name="habit_checkin_uniq"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HabitEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("client_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("amount", models.CharField(blank=True, max_length=80)),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="«Что случилось» — без осуждающих формулировок.",
                    ),
                ),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="habits.habit",
                    ),
                ),
                (
                    "trigger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.cravingtrigger",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "client_id"),
                        name="habits_habitepisode_client_uniq",
                    )
                ],
            },
        ),
    ]
