# Generated by Django 5.2.17 on 2026-09-18 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("op_id", models.UUIDField()),
                ("entity", models.CharField(max_length=60)),
                ("client_id", models.UUIDField(blank=True, null=True)),
                ("op", models.CharField(default="upsert", max_length=10)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "op_id"), name="sync_operation_uniq"
                    )
                ],
            },
        ),
    ]
