# Generated by Django 5.2.17 on 2026-09-18 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=60)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("required", "обязательный"),
                            ("main", "основной"),
                            ("optional", "по остатку сил"),
                        ],
                        default="main",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=120)),
                ("aliases", models.JSONField(blank=True, default=list)),
                (
                    "load_type",
                    models.CharField(
                        choices=[
                            ("weight_reps", "вес × повторы"),
                            ("time", "время"),
                            ("bodyweight_reps", "повторы без веса"),
                            ("distance", "дистанция"),
                        ],
                        default="weight_reps",
                        max_length=20,
                    ),
                ),
                (
                    "is_unilateral",
                    models.BooleanField(
                        default=False,
                        help_text="Вес указывается на одну сторону. Без этого флага тоннаж считается вдвое меньше реального (молотки «16 кг на руку»).",
                    ),
                ),
                (
                    "bodyweight_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Доля веса тела для подтягиваний/отжиманий.",
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("default_rest_seconds", models.PositiveIntegerField(default=90)),
                ("instructions", models.TextField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exercises",
                        to="catalog.equipment",
                    ),
                ),
                (
                    "movement_tags",
                    models.ManyToManyField(
                        blank=True, related_name="exercises", to="catalog.movementtag"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseMuscle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("primary", "первичная"), ("secondary", "вторичная")],
                        default="primary",
                        max_length=10,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="muscle_links",
                        to="training.exercise",
                    ),
                ),
                (
                    "muscle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.muscle"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exercise",
            name="muscles",
            field=models.ManyToManyField(
                related_name="exercises",
                through="training.ExerciseMuscle",
                to="catalog.muscle",
            ),
        ),
        migrations.CreateModel(
            name="Gym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("work", "рабочий"),
                            ("home", "домашний"),
                            ("travel", "в поездке"),
                            ("other", "другой"),
                        ],
                        default="work",
                        max_length=10,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="GymExerciseProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("weight_steps", models.JSONField(blank=True, default=list)),
                (
                    "step_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "last_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("last_reps", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "last_duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("machine_number", models.CharField(blank=True, max_length=20)),
                ("seat_settings", models.CharField(blank=True, max_length=120)),
                ("grip", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="gym_setups/"),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gym_profiles",
                        to="training.exercise",
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_profiles",
                        to="training.gym",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgressionSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("increase", "можно прибавить"),
                            ("stall", "застой"),
                            ("deload", "пора разгрузиться"),
                            ("spike_warning", "резкий скачок"),
                            ("imbalance", "дисбаланс объёма"),
                            ("order_hint", "переставить выше"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "suggested_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("message", models.CharField(max_length=300)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_on", models.DateField(auto_now_add=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="training.exercise",
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="training.gym",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="SessionExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("client_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "block_priority",
                    models.CharField(
                        choices=[
                            ("required", "обязательный"),
                            ("main", "основной"),
                            ("optional", "по остатку сил"),
                        ],
                        default="main",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "не начато"),
                            ("done", "сделано"),
                            ("skipped", "пропущено"),
                            ("failed", "не смог"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("fail_reason_note", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session_entries",
                        to="training.exercise",
                    ),
                ),
                (
                    "fail_reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.failreason",
                    ),
                ),
                (
                    "substituted_for",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substitutions",
                        to="training.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SetLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("client_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("set_number", models.PositiveSmallIntegerField(default=1)),
                ("is_warmup", models.BooleanField(default=False)),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "weight_is_per_side",
                    models.BooleanField(
                        default=False,
                        help_text="Снапшот флага «одностороннее» на момент записи — изменение упражнения потом не ломает историю.",
                    ),
                ),
                ("reps", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("distance_m", models.PositiveIntegerField(blank=True, null=True)),
                ("rir", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "session_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="training.sessionexercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["set_number", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("max_weight", "максимальный вес"),
                            ("max_reps", "максимум повторов"),
                            ("max_duration_seconds", "максимальное удержание"),
                            ("est_1rm", "расчётный 1ПМ"),
                            ("max_set_volume", "максимальный объём подхода"),
                        ],
                        max_length=24,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=9)),
                ("achieved_on", models.DateField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="training.exercise",
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="training.gym",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "set_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="training.setlog",
                    ),
                ),
            ],
            options={
                "ordering": ["-achieved_on"],
            },
        ),
        migrations.CreateModel(
            name="TemplateExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("target_sets", models.PositiveSmallIntegerField(default=3)),
                (
                    "target_reps_min",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "target_reps_max",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("target_seconds", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "target_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("rest_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="training.templateblock",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="training.exercise",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="sessionexercise",
            name="template_exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="training.templateexercise",
            ),
        ),
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("client_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("date", models.DateField(db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "запланирована"),
                            ("in_progress", "идёт"),
                            ("completed", "завершена"),
                            ("abandoned", "прервана"),
                        ],
                        default="planned",
                        max_length=12,
                    ),
                ),
                (
                    "wellbeing_1_10",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_training_while_injured", models.BooleanField(default=False)),
                (
                    "tonnage_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=9),
                ),
                ("working_sets_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "gym",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="training.gym",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-started_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="sessionexercise",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="training.workoutsession",
            ),
        ),
        migrations.CreateModel(
            name="WorkoutTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                (
                    "duration_limit_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="training.workouttemplate",
            ),
        ),
        migrations.CreateModel(
            name="TemplateSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekday", models.PositiveSmallIntegerField()),
                ("is_auto_repeating", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="training.workouttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday"],
            },
        ),
        migrations.AddField(
            model_name="templateblock",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="training.workouttemplate",
            ),
        ),
        migrations.CreateModel(
            name="PlannedExclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField(blank=True, null=True)),
                ("reason", models.CharField(max_length=200)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exclusions",
                        to="training.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exclusions",
                        to="training.workouttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_from"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseAlternative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "alternative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternative_for",
                        to="training.exercise",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternatives",
                        to="training.exercise",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_alternatives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("exercise", "alternative", "owner"),
                        name="exercise_alt_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("exercise", models.F("alternative")), _negated=True
                        ),
                        name="exercise_alt_not_self",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="exercisemuscle",
            constraint=models.UniqueConstraint(
                fields=("exercise", "muscle"), name="exercise_muscle_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["owner", "is_archived"], name="training_ex_owner_i_b91949_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="exercise",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="exercise_owner_name_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="gym",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="gym_user_name_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="gymexerciseprofile",
            constraint=models.UniqueConstraint(
                fields=("user", "gym", "exercise"), name="gym_exercise_profile_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="progressionsuggestion",
            index=models.Index(
                fields=["user", "kind", "created_on"],
                name="training_pr_user_id_2de3df_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="setlog",
            constraint=models.UniqueConstraint(
                fields=("user", "client_id"), name="training_setlog_client_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="setlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rir__isnull", True), ("rir__lte", 10), _connector="OR"
                ),
                name="setlog_rir_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="personalrecord",
            constraint=models.UniqueConstraint(
                fields=("user", "exercise", "kind"), name="personal_record_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionexercise",
            constraint=models.UniqueConstraint(
                fields=("user", "client_id"),
                name="training_sessionexercise_client_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="workoutsession",
            index=models.Index(
                fields=["user", "date"], name="training_wo_user_id_e35552_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workoutsession",
            constraint=models.UniqueConstraint(
                fields=("user", "client_id"), name="training_workoutsession_client_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="templateschedule",
            constraint=models.UniqueConstraint(
                fields=("template", "weekday"), name="template_schedule_uniq"
            ),
        ),
    ]
