# Generated by Django 5.2.17 on 2026-09-18 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BodyPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("name_ru", models.CharField(max_length=60)),
                ("name_en", models.CharField(max_length=60)),
                ("region", models.CharField(max_length=20)),
                ("svg_path_id", models.CharField(blank=True, max_length=40)),
                (
                    "view",
                    models.CharField(
                        choices=[
                            ("front", "спереди"),
                            ("back", "сзади"),
                            ("both", "обе"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["region", "code"],
            },
        ),
        migrations.CreateModel(
            name="CravingTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("name_ru", models.CharField(max_length=60)),
                ("name_en", models.CharField(max_length=60)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("name_ru", models.CharField(max_length=60)),
                ("name_en", models.CharField(max_length=60)),
            ],
            options={
                "verbose_name_plural": "equipment",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="FailReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("name_ru", models.CharField(max_length=80)),
                ("name_en", models.CharField(max_length=80)),
                ("counts_against_discipline", models.BooleanField(default=True)),
                ("suggests_alternative", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="HealthTimelineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("habit_kind", models.SlugField(max_length=40)),
                ("hours_after", models.PositiveIntegerField()),
                ("title_ru", models.CharField(max_length=120)),
                ("title_en", models.CharField(max_length=120)),
                ("description_ru", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["habit_kind", "hours_after"],
            },
        ),
        migrations.CreateModel(
            name="MovementTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("name_ru", models.CharField(max_length=60)),
                ("name_en", models.CharField(max_length=60)),
                ("is_push", models.BooleanField(default=False)),
                ("is_pull", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Muscle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("name_ru", models.CharField(max_length=60)),
                ("name_en", models.CharField(max_length=60)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("chest", "грудь"),
                            ("back", "спина"),
                            ("shoulders", "плечи"),
                            ("biceps", "бицепс"),
                            ("triceps", "трицепс"),
                            ("quads", "квадрицепс"),
                            ("hamstrings", "бицепс бедра"),
                            ("glutes", "ягодицы"),
                            ("calves", "икры"),
                            ("core", "кор"),
                            ("forearms", "предплечья"),
                            ("neck", "шея"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["group", "code"],
            },
        ),
        migrations.CreateModel(
            name="BodyPartMovementRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("caution", "осторожно"),
                            ("avoid", "лучше исключить"),
                        ],
                        default="caution",
                        max_length=10,
                    ),
                ),
                (
                    "body_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="catalog.bodypart",
                    ),
                ),
                (
                    "movement_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="catalog.movementtag",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("body_part", "movement_tag"),
                        name="bodypart_movement_uniq",
                    )
                ],
            },
        ),
    ]
