/**
 * Роли мышц в упражнениях — библиотека мышечной карты (ветка main,
 * js/data.js, 71 упражнение) и сопоставление с упражнениями справочника
 * приложения. Используется для расчёта нагрузки по реальным подходам.
 */
import type { MuscleId } from "./muscles";

export interface LibraryExercise {
  id: string;
  name: string;
  cat: string;
  p: MuscleId[];
  s: MuscleId[];
  t: MuscleId[];
}

const HAMS: MuscleId[] = ["biceps-femoris", "semitendinosus", "semimembranosus"];
const QUADS_V: MuscleId[] = ["vastus-lateralis", "vastus-medialis"];
const TRI: MuscleId[] = ["triceps-lateral", "triceps-medial"];

export const LIBRARY: LibraryExercise[] = [
  // ---- Грудь
  { id: "bench", name: "Жим штанги лёжа", cat: "chest",
    p: ["pec-mid", "pec-lower"], s: ["pec-upper", "delt-front", ...TRI], t: ["triceps-long", "serratus", "lats"] },
  { id: "incline-bench", name: "Жим на наклонной скамье", cat: "chest",
    p: ["pec-upper"], s: ["pec-mid", "delt-front", ...TRI], t: ["triceps-long", "serratus"] },
  { id: "decline-bench", name: "Жим на скамье с отрицательным наклоном", cat: "chest",
    p: ["pec-lower", "pec-mid"], s: TRI, t: ["delt-front", "triceps-long"] },
  { id: "db-press", name: "Жим гантелей лёжа", cat: "chest",
    p: ["pec-mid", "pec-lower"], s: ["pec-upper", "delt-front", ...TRI], t: ["serratus", "biceps"] },
  { id: "dips", name: "Отжимания на брусьях (грудной стиль)", cat: "chest",
    p: ["pec-lower", ...TRI], s: ["pec-mid", "delt-front", "triceps-long"], t: ["serratus", "trap-lower", "rhomboids"] },
  { id: "pushups", name: "Отжимания от пола", cat: "chest",
    p: ["pec-mid"], s: ["pec-upper", "pec-lower", "delt-front", ...TRI], t: ["rectus-abdominis", "obliques", "serratus"] },
  { id: "cable-fly", name: "Сведение рук в кроссовере", cat: "chest",
    p: ["pec-mid", "pec-lower"], s: ["pec-upper", "delt-front"], t: ["biceps", "serratus"] },
  { id: "pec-deck", name: "Бабочка (пек-дек)", cat: "chest",
    p: ["pec-mid"], s: ["pec-upper", "pec-lower"], t: ["delt-front"] },
  { id: "pullover", name: "Пуловер с гантелью", cat: "chest",
    p: ["lats", "pec-lower"], s: ["triceps-long", "teres-major", "serratus"], t: ["pec-mid", "rectus-abdominis"] },

  // ---- Спина
  { id: "pullups", name: "Подтягивания широким хватом", cat: "back",
    p: ["lats", "teres-major"], s: ["biceps", "brachialis", "brachioradialis", "rhomboids", "trap-lower", "delt-rear"],
    t: ["forearm-flexors", "rectus-abdominis", "infraspinatus", "teres-minor"] },
  { id: "chinups", name: "Подтягивания обратным хватом", cat: "back",
    p: ["lats", "biceps"], s: ["brachialis", "teres-major", "pec-lower", "rhomboids"], t: ["forearm-flexors", "trap-lower", "rectus-abdominis"] },
  { id: "lat-pulldown", name: "Тяга верхнего блока", cat: "back",
    p: ["lats"], s: ["teres-major", "biceps", "brachialis", "rhomboids", "trap-lower"], t: ["delt-rear", "forearm-flexors"] },
  { id: "barbell-row", name: "Тяга штанги в наклоне", cat: "back",
    p: ["lats", "rhomboids", "trap-middle"], s: ["delt-rear", "teres-major", "biceps", "brachialis", "erectors", "infraspinatus"],
    t: [...HAMS, "glute-max", "forearm-flexors", "brachioradialis"] },
  { id: "db-row", name: "Тяга гантели одной рукой", cat: "back",
    p: ["lats", "rhomboids"], s: ["trap-middle", "delt-rear", "teres-major", "biceps", "brachialis"], t: ["obliques", "erectors", "forearm-flexors"] },
  { id: "cable-row", name: "Тяга горизонтального блока", cat: "back",
    p: ["rhomboids", "trap-middle", "lats"], s: ["delt-rear", "biceps", "brachialis", "teres-major", "trap-lower"], t: ["erectors", "forearm-flexors"] },
  { id: "face-pull", name: "Тяга каната к лицу (face pull)", cat: "shoulders",
    p: ["delt-rear", "infraspinatus", "teres-minor"], s: ["trap-middle", "rhomboids", "trap-lower"], t: ["biceps", "forearm-extensors"] },
  { id: "shrugs", name: "Шраги со штангой", cat: "traps",
    p: ["trap-upper"], s: ["trap-middle"], t: ["forearm-flexors", "brachioradialis", "rhomboids"] },
  { id: "deadlift", name: "Становая тяга", cat: "lowerback",
    p: ["glute-max", "erectors", ...HAMS, "adductor-magnus"],
    s: [...QUADS_V, "trap-upper", "trap-middle", "lats", "forearm-flexors"],
    t: ["rectus-femoris", "rectus-abdominis", "obliques", "rhomboids", "brachioradialis", "gastrocnemius", "soleus"] },
  { id: "hyperext", name: "Гиперэкстензия", cat: "lowerback",
    p: ["erectors"], s: ["glute-max", ...HAMS], t: ["adductor-magnus"] },
  { id: "good-morning", name: "Наклоны со штангой (гуд морнинг)", cat: "lowerback",
    p: ["erectors", ...HAMS], s: ["glute-max", "adductor-magnus"], t: ["rectus-abdominis", "obliques", "trap-middle"] },

  // ---- Плечи
  { id: "ohp", name: "Армейский жим стоя", cat: "shoulders",
    p: ["delt-front"], s: ["delt-side", ...TRI, "triceps-long", "pec-upper", "trap-upper", "serratus"],
    t: ["rectus-abdominis", "obliques", "erectors", "glute-max", "trap-lower"] },
  { id: "db-shoulder-press", name: "Жим гантелей сидя", cat: "shoulders",
    p: ["delt-front"], s: ["delt-side", ...TRI, "pec-upper"], t: ["triceps-long", "trap-upper", "serratus"] },
  { id: "lateral-raise", name: "Махи гантелями в стороны", cat: "shoulders",
    p: ["delt-side"], s: ["delt-front", "trap-upper"], t: ["delt-rear", "serratus", "forearm-extensors"] },
  { id: "front-raise", name: "Подъём гантелей перед собой", cat: "shoulders",
    p: ["delt-front"], s: ["pec-upper", "delt-side"], t: ["serratus", "trap-upper"] },
  { id: "reverse-fly", name: "Разведение гантелей в наклоне", cat: "shoulders",
    p: ["delt-rear"], s: ["infraspinatus", "teres-minor", "trap-middle", "rhomboids"], t: ["delt-side", "erectors"] },
  { id: "upright-row", name: "Тяга штанги к подбородку", cat: "shoulders",
    p: ["delt-side", "trap-upper"], s: ["delt-front", "biceps", "brachialis", "brachioradialis"], t: ["forearm-flexors", "trap-middle"] },
  { id: "y-raise", name: "Y-подъёмы лёжа на наклонной", cat: "traps",
    p: ["trap-lower"], s: ["trap-middle", "delt-side", "delt-rear"], t: ["infraspinatus", "teres-minor", "serratus"] },
  { id: "ext-rotation", name: "Наружная ротация плеча на блоке", cat: "rotator",
    p: ["infraspinatus", "teres-minor"], s: ["delt-rear"], t: ["trap-middle", "rhomboids"] },

  // ---- Руки
  { id: "barbell-curl", name: "Подъём штанги на бицепс", cat: "biceps",
    p: ["biceps"], s: ["brachialis", "brachioradialis"], t: ["delt-front", "forearm-flexors"] },
  { id: "hammer-curl", name: "Молотки с гантелями", cat: "biceps",
    p: ["brachialis", "brachioradialis"], s: ["biceps"], t: ["forearm-extensors", "forearm-flexors"] },
  { id: "preacher-curl", name: "Сгибания на скамье Скотта", cat: "biceps",
    p: ["biceps", "brachialis"], s: ["brachioradialis"], t: ["forearm-flexors"] },
  { id: "concentration-curl", name: "Концентрированные сгибания", cat: "biceps",
    p: ["biceps"], s: ["brachialis"], t: ["brachioradialis"] },
  { id: "close-grip-bench", name: "Жим лёжа узким хватом", cat: "triceps",
    p: TRI, s: ["triceps-long", "pec-mid", "pec-lower", "delt-front"], t: ["pec-upper", "serratus"] },
  { id: "skull-crusher", name: "Французский жим лёжа", cat: "triceps",
    p: ["triceps-long", "triceps-medial"], s: ["triceps-lateral"], t: ["forearm-flexors", "lats"] },
  { id: "pushdown", name: "Разгибания рук на блоке", cat: "triceps",
    p: TRI, s: ["triceps-long"], t: ["forearm-extensors", "rectus-abdominis"] },
  { id: "overhead-ext", name: "Разгибание руки из-за головы", cat: "triceps",
    p: ["triceps-long"], s: TRI, t: ["rectus-abdominis", "serratus"] },
  { id: "bench-dips", name: "Обратные отжимания от скамьи", cat: "triceps",
    p: TRI, s: ["triceps-long", "delt-front", "pec-lower"], t: ["rhomboids"] },
  { id: "wrist-curl", name: "Сгибания запястий", cat: "forearms",
    p: ["forearm-flexors"], s: [], t: ["brachioradialis"] },
  { id: "reverse-wrist-curl", name: "Разгибания запястий", cat: "forearms",
    p: ["forearm-extensors"], s: ["brachioradialis"], t: [] },
  { id: "reverse-curl", name: "Сгибания обратным хватом", cat: "forearms",
    p: ["brachioradialis", "brachialis"], s: ["forearm-extensors", "biceps"], t: [] },
  { id: "farmers-walk", name: "Прогулка фермера", cat: "forearms",
    p: ["forearm-flexors", "trap-upper"], s: ["trap-middle", "obliques", "erectors", "brachioradialis", "forearm-extensors"],
    t: ["glute-med", "gastrocnemius", "soleus", "rectus-abdominis", "vastus-lateralis"] },

  // ---- Кор
  { id: "scap-pushup", name: "Отжимания с протракцией лопаток", cat: "core",
    p: ["serratus"], s: ["pec-mid", "delt-front"], t: ["rectus-abdominis", "obliques", ...TRI] },
  { id: "crunch", name: "Скручивания", cat: "core",
    p: ["rectus-abdominis"], s: ["obliques"], t: [] },
  { id: "hanging-leg-raise", name: "Подъём ног в висе", cat: "core",
    p: ["rectus-abdominis", "iliopsoas"], s: ["obliques", "rectus-femoris", "tfl"], t: ["forearm-flexors", "lats", "sartorius"] },
  { id: "lying-leg-raise", name: "Подъём ног лёжа", cat: "hips",
    p: ["iliopsoas", "rectus-abdominis"], s: ["rectus-femoris", "sartorius"], t: ["obliques", "tfl"] },
  { id: "plank", name: "Планка", cat: "core",
    p: ["rectus-abdominis"], s: ["obliques", "serratus", "delt-front"], t: ["erectors", "glute-max", "rectus-femoris", "pec-mid"] },
  { id: "side-plank", name: "Боковая планка", cat: "core",
    p: ["obliques"], s: ["glute-med", "rectus-abdominis"], t: ["delt-side", "tfl", "erectors"] },
  { id: "russian-twist", name: "Русские скручивания", cat: "core",
    p: ["obliques"], s: ["rectus-abdominis"], t: ["iliopsoas"] },
  { id: "ab-wheel", name: "Ролик для пресса", cat: "core",
    p: ["rectus-abdominis"], s: ["obliques", "lats", "serratus"], t: ["delt-front", "triceps-long", "iliopsoas", "rectus-femoris"] },
  { id: "woodchop", name: "Дровосек на блоке", cat: "core",
    p: ["obliques"], s: ["rectus-abdominis", "serratus"], t: ["delt-front", "glute-med"] },
  { id: "neck-flexion", name: "Сгибание шеи с отягощением", cat: "neck",
    p: ["sternocleidomastoid"], s: [], t: ["trap-upper"] },
  { id: "neck-extension", name: "Разгибание шеи с отягощением", cat: "neck",
    p: ["trap-upper"], s: ["sternocleidomastoid"], t: [] },

  // ---- Ноги
  { id: "squat", name: "Приседания со штангой", cat: "quads",
    p: [...QUADS_V, "glute-max", "adductor-magnus"], s: ["rectus-femoris", "adductors", "erectors"],
    t: [...HAMS, "soleus", "gastrocnemius", "rectus-abdominis", "obliques"] },
  { id: "front-squat", name: "Фронтальные приседания", cat: "quads",
    p: [...QUADS_V, "rectus-femoris"], s: ["glute-max", "adductor-magnus", "erectors", "rectus-abdominis"],
    t: ["trap-upper", "trap-middle", "obliques", "soleus"] },
  { id: "leg-press", name: "Жим ногами", cat: "quads",
    p: [...QUADS_V, "glute-max"], s: ["rectus-femoris", "adductor-magnus", "adductors"], t: ["biceps-femoris", "gastrocnemius"] },
  { id: "lunges", name: "Выпады с гантелями", cat: "quads",
    p: [...QUADS_V, "glute-max"], s: ["rectus-femoris", "adductor-magnus", "glute-med"], t: ["obliques", "gastrocnemius", "soleus", "tfl", "adductors", "forearm-flexors"] },
  { id: "bulgarian", name: "Болгарские сплит-приседания", cat: "quads",
    p: [...QUADS_V, "glute-max"], s: ["rectus-femoris", "glute-med", "adductor-magnus"], t: ["tfl", "soleus", "obliques", "iliopsoas"] },
  { id: "leg-extension", name: "Разгибание ног в тренажёре", cat: "quads",
    p: ["rectus-femoris", ...QUADS_V], s: [], t: [] },
  { id: "rdl", name: "Румынская тяга", cat: "hamstrings",
    p: [...HAMS, "glute-max"], s: ["erectors", "adductor-magnus"], t: ["forearm-flexors", "trap-upper", "lats", "trap-middle"] },
  { id: "leg-curl", name: "Сгибание ног лёжа", cat: "hamstrings",
    p: HAMS, s: ["gastrocnemius"], t: ["sartorius"] },
  { id: "seated-leg-curl", name: "Сгибание ног сидя", cat: "hamstrings",
    p: HAMS, s: [], t: ["gastrocnemius", "sartorius"] },
  { id: "nordic", name: "Нордические сгибания", cat: "hamstrings",
    p: HAMS, s: ["gastrocnemius"], t: ["glute-max", "erectors"] },
  { id: "hip-thrust", name: "Ягодичный мост со штангой", cat: "glutes",
    p: ["glute-max"], s: [...HAMS, "adductor-magnus", "glute-med"], t: [...QUADS_V, "rectus-abdominis", "erectors"] },
  { id: "kb-swing", name: "Махи гирей", cat: "glutes",
    p: ["glute-max", ...HAMS], s: ["erectors", "delt-front", "adductor-magnus"], t: ["forearm-flexors", "trap-upper", "obliques", "vastus-lateralis"] },
  { id: "hip-abduction", name: "Отведение бедра в тренажёре", cat: "glutes",
    p: ["glute-med", "tfl"], s: ["glute-max"], t: [] },
  { id: "cable-hip-flexion", name: "Сгибание бедра на нижнем блоке", cat: "hips",
    p: ["iliopsoas"], s: ["rectus-femoris", "sartorius", "tfl"], t: ["rectus-abdominis", "glute-med"] },
  { id: "hip-adduction", name: "Сведение ног в тренажёре", cat: "hips",
    p: ["adductors", "adductor-magnus"], s: [], t: ["sartorius"] },
  { id: "calf-raise", name: "Подъём на носки стоя", cat: "calves",
    p: ["gastrocnemius"], s: ["soleus"], t: ["peroneus", "tibialis"] },
  { id: "seated-calf", name: "Подъём на носки сидя", cat: "calves",
    p: ["soleus"], s: ["gastrocnemius"], t: ["peroneus"] },
  { id: "tibialis-raise", name: "Подъём носков (тибиалис)", cat: "calves",
    p: ["tibialis"], s: [], t: ["peroneus"] },
  { id: "ankle-eversion", name: "Отведение стопы с резиной (эверсия)", cat: "calves",
    p: ["peroneus"], s: [], t: ["tibialis"] },
];
