# Generated by Django 5.2.17 on 2026-09-18 20:29

import apps.accounts.models
import apps.accounts.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "today_blocks",
                    models.JSONField(default=apps.accounts.models.default_today_blocks),
                ),
                ("protein_target_g", models.PositiveIntegerField(default=150)),
                ("track_calories", models.BooleanField(default=False)),
                ("calorie_target", models.PositiveIntegerField(blank=True, null=True)),
                ("water_target_ml", models.PositiveIntegerField(default=2000)),
                ("water_glass_ml", models.PositiveIntegerField(default=250)),
                (
                    "free_meal_weekday",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("bedtime_goal", models.TimeField(default="23:30")),
                ("wake_goal", models.TimeField(default="07:00")),
                ("sleep_target_minutes", models.PositiveIntegerField(default=480)),
                ("commute_home_minutes", models.PositiveIntegerField(default=60)),
                ("wind_down_minutes", models.PositiveIntegerField(default=60)),
                ("rest_default_seconds", models.PositiveIntegerField(default=90)),
                (
                    "rest_presets",
                    models.JSONField(default=apps.accounts.models.default_rest_presets),
                ),
                ("ask_rir", models.BooleanField(default=True)),
                ("count_bodyweight_in_tonnage", models.BooleanField(default=False)),
                (
                    "fail_reason_overrides",
                    models.JSONField(
                        default=dict,
                        help_text="Переопределение того, какие причины «не смог» влияют на дисциплину.",
                    ),
                ),
                ("diary_lock_enabled", models.BooleanField(default=False)),
                ("diary_pin_hash", models.CharField(blank=True, max_length=128)),
                ("diary_biometric", models.BooleanField(default=False)),
                ("week_starts_on", models.PositiveSmallIntegerField(default=1)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("auto", "auto"),
                            ("light", "light"),
                            ("dark", "dark"),
                        ],
                        default="auto",
                        max_length=8,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[apps.accounts.validators.validate_username],
                        verbose_name="ник",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="телефон",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="отображаемое имя"
                    ),
                ),
                (
                    "apple_sub",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=80)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("prefix", models.CharField(max_length=12)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("read", "только чтение"),
                            ("write", "чтение и запись"),
                        ],
                        default="read",
                        max_length=5,
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeatureInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("feature", models.CharField(db_index=True, max_length=64)),
                ("message", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("male", "мужской"),
                            ("female", "женский"),
                            ("other", "другой"),
                            ("unspecified", "не указан"),
                        ],
                        default="unspecified",
                        max_length=12,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "start_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("timezone", models.CharField(default="Europe/Moscow", max_length=64)),
                (
                    "unit_system",
                    models.CharField(
                        choices=[("metric", "метрическая"), ("imperial", "имперская")],
                        default="metric",
                        max_length=10,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ru", "ru"), ("en", "en")], default="ru", max_length=5
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("avatar_seed", models.CharField(blank=True, max_length=16)),
                (
                    "goal_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "goal_bodyfat_pct",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("goal_deadline", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("slug", models.CharField(db_index=True, max_length=32, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("weekly_report", "недельный отчёт"),
                            ("workout", "тренировка"),
                            ("context", "контекст для ИИ"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("period_from", models.DateField(blank=True, null=True)),
                ("period_to", models.DateField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
