# Generated by Django 5.2.17 on 2026-09-18 20:29

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="default_gym",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="training.gym",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"),
                name="user_username_ci_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("email__isnull", False), ("phone__isnull", False), _connector="OR"
                ),
                name="user_email_or_phone_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="featureinterest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("message", "")),
                fields=("user", "feature"),
                name="feature_interest_unique_subscription",
            ),
        ),
    ]
