# Generated by Django 5.2.17 on 2026-09-18 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="bedtime_goal",
            field=models.TimeField(default=datetime.time(23, 30)),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="wake_goal",
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
