# Generated by Django 5.2.17 on 2026-09-23 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_users_onboarded(apps, schema_editor):
    """Кто уже пользуется приложением, опрос не проходит: всё настроено руками."""
    from django.utils import timezone

    UserSettings = apps.get_model("accounts", "UserSettings")
    UserSettings.objects.filter(onboarding_completed_at__isnull=True).update(
        onboarding_completed_at=timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_usersettings_bedtime_goal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="onboarding_answers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="onboarding_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="InviteCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("code", models.CharField(blank=True, max_length=32, unique=True)),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="для кого"
                    ),
                ),
                ("max_uses", models.PositiveIntegerField(default=1)),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InviteRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="accounts.invitecode",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_redemption",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-redeemed_at"],
            },
        ),
        migrations.RunPython(mark_existing_users_onboarded, migrations.RunPython.noop),
    ]
