# Generated by Django 5.2.17 on 2026-09-18 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("shortcut", "Apple Shortcuts"),
                            ("xml", "export.zip из «Здоровья»"),
                        ],
                        max_length=12,
                    ),
                ),
                ("records_created", models.PositiveIntegerField(default=0)),
                ("records_skipped", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="ok", max_length=12)),
                ("error", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IllnessPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField(blank=True, null=True)),
                ("label", models.CharField(blank=True, max_length=80)),
                ("note", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_from"],
            },
        ),
        migrations.CreateModel(
            name="HealthMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("steps", "шаги"),
                            ("resting_hr", "пульс покоя"),
                            ("hr_avg", "средний пульс"),
                            ("active_energy_kcal", "активные калории"),
                            ("workout_minutes", "минуты тренировок"),
                            ("distance_m", "дистанция"),
                            ("hrv_ms", "вариабельность пульса"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("source", models.CharField(default="shortcut", max_length=20)),
                ("external_id", models.CharField(blank=True, max_length=128)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "kind", "date"],
                        name="recovery_he_user_id_bdca1e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date", "kind", "source", "external_id"),
                        name="health_metric_dedupe",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SleepEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("client_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "night_of",
                    models.DateField(
                        db_index=True, help_text="Дата вечера, а не утра."
                    ),
                ),
                ("bed_time", models.DateTimeField(blank=True, null=True)),
                ("wake_time", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "quality_1_5",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("awakenings", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "вручную"),
                            ("shortcut", "Apple Shortcuts"),
                            ("healthkit", "Apple Health"),
                        ],
                        default="manual",
                        max_length=12,
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=128)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-night_of"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "client_id"),
                        name="recovery_sleepentry_client_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("user", "night_of", "source"),
                        name="sleep_entry_night_source_uniq",
                    ),
                ],
            },
        ),
    ]
