"""Справочники и предзаполненная библиотека упражнений."""

MUSCLES = [
    ("chest_pec", "Большая грудная", "Pectoralis major", "chest"),
    ("chest_pec_minor", "Малая грудная", "Pectoralis minor", "chest"),
    ("back_lats", "Широчайшие", "Latissimus dorsi", "back"),
    ("back_traps", "Трапеции", "Trapezius", "back"),
    ("back_rhomboids", "Ромбовидные", "Rhomboids", "back"),
    ("back_erectors", "Разгибатели спины", "Erector spinae", "back"),
    ("delts_front", "Передняя дельта", "Anterior deltoid", "shoulders"),
    ("delts_side", "Средняя дельта", "Lateral deltoid", "shoulders"),
    ("delts_rear", "Задняя дельта", "Posterior deltoid", "shoulders"),
    ("biceps", "Бицепс", "Biceps brachii", "biceps"),
    ("brachialis", "Плечевая мышца", "Brachialis", "biceps"),
    ("triceps", "Трицепс", "Triceps brachii", "triceps"),
    ("forearms", "Предплечья", "Forearms", "forearms"),
    ("quads", "Квадрицепс", "Quadriceps", "quads"),
    ("hamstrings", "Бицепс бедра", "Hamstrings", "hamstrings"),
    ("glutes", "Ягодичные", "Glutes", "glutes"),
    ("calves", "Икроножные", "Calves", "calves"),
    ("abs", "Прямая мышца живота", "Rectus abdominis", "core"),
    ("obliques", "Косые живота", "Obliques", "core"),
    ("neck", "Шея", "Neck", "neck"),
]

EQUIPMENT = [
    ("barbell", "Штанга", "Barbell"),
    ("dumbbell", "Гантели", "Dumbbells"),
    ("machine", "Тренажёр", "Machine"),
    ("cable", "Блок", "Cable"),
    ("bodyweight", "Вес тела", "Bodyweight"),
    ("kettlebell", "Гиря", "Kettlebell"),
    ("band", "Резина", "Band"),
    ("other", "Другое", "Other"),
]

BODY_PARTS = [
    ("shoulder_l", "Плечо левое", "Left shoulder", "upper", "both"),
    ("shoulder_r", "Плечо правое", "Right shoulder", "upper", "both"),
    ("elbow_l", "Локоть левый", "Left elbow", "upper", "both"),
    ("elbow_r", "Локоть правый", "Right elbow", "upper", "both"),
    ("wrist_l", "Запястье левое", "Left wrist", "upper", "both"),
    ("wrist_r", "Запястье правое", "Right wrist", "upper", "both"),
    ("neck", "Шея", "Neck", "head", "both"),
    ("upper_back", "Верх спины", "Upper back", "trunk", "back"),
    ("lower_back", "Поясница", "Lower back", "trunk", "back"),
    ("chest", "Грудь", "Chest", "trunk", "front"),
    ("abdomen", "Живот", "Abdomen", "trunk", "front"),
    ("hip_l", "Бедро левое", "Left hip", "lower", "both"),
    ("hip_r", "Бедро правое", "Right hip", "lower", "both"),
    ("knee_l", "Колено левое", "Left knee", "lower", "front"),
    ("knee_r", "Колено правое", "Right knee", "lower", "front"),
    ("ankle_l", "Голеностоп левый", "Left ankle", "lower", "both"),
    ("ankle_r", "Голеностоп правый", "Right ankle", "lower", "both"),
]

MOVEMENT_TAGS = [
    ("overhead", "Над головой", "Overhead", True, False),
    ("horizontal_push", "Жим горизонтальный", "Horizontal push", True, False),
    ("vertical_push", "Жим вертикальный", "Vertical push", True, False),
    ("horizontal_pull", "Тяга горизонтальная", "Horizontal pull", False, True),
    ("vertical_pull", "Тяга вертикальная", "Vertical pull", False, True),
    ("hip_hinge", "Наклон с тазом", "Hip hinge", False, False),
    ("knee_dominant", "Приседания и жимы ногами", "Knee dominant", False, False),
    ("spinal_load", "Осевая нагрузка на позвоночник", "Spinal load", False, False),
    ("spinal_flexion", "Сгибание позвоночника", "Spinal flexion", False, False),
    ("rotation", "Ротация корпуса", "Rotation", False, False),
    ("impact", "Ударная нагрузка", "Impact", False, False),
    ("elbow_flexion", "Сгибание в локте", "Elbow flexion", False, False),
    ("wrist_load", "Нагрузка на запястье", "Wrist load", False, False),
]

# Какие движения опасны при травме какой зоны.
BODY_PART_RISKS = [
    ("shoulder_l", "overhead", "avoid"), ("shoulder_r", "overhead", "avoid"),
    ("shoulder_l", "vertical_push", "avoid"), ("shoulder_r", "vertical_push", "avoid"),
    ("shoulder_l", "horizontal_push", "caution"), ("shoulder_r", "horizontal_push", "caution"),
    ("shoulder_l", "vertical_pull", "caution"), ("shoulder_r", "vertical_pull", "caution"),
    ("elbow_l", "elbow_flexion", "caution"), ("elbow_r", "elbow_flexion", "caution"),
    ("wrist_l", "wrist_load", "caution"), ("wrist_r", "wrist_load", "caution"),
    ("lower_back", "spinal_load", "avoid"),
    ("lower_back", "hip_hinge", "avoid"),
    ("lower_back", "spinal_flexion", "caution"),
    ("lower_back", "rotation", "caution"),
    ("upper_back", "spinal_load", "caution"),
    ("knee_l", "knee_dominant", "avoid"), ("knee_r", "knee_dominant", "avoid"),
    ("knee_l", "impact", "avoid"), ("knee_r", "impact", "avoid"),
    ("ankle_l", "impact", "avoid"), ("ankle_r", "impact", "avoid"),
    ("neck", "overhead", "caution"), ("neck", "spinal_load", "caution"),
]

# counts_against_discipline=False — пропуск по внешней причине
# не портит статистику дисциплины.
FAIL_REASONS = [
    ("machine_busy", "Тренажёр занят", "Machine busy", False, True, 0),
    ("pain", "Боль", "Pain", False, True, 1),
    ("no_time", "Не хватило времени", "Ran out of time", False, False, 2),
    ("illness", "Плохо себя чувствую", "Feeling ill", False, False, 3),
    ("no_energy", "Нет сил", "No energy", True, False, 4),
    ("forgot", "Забыл", "Forgot", True, False, 5),
    ("other", "Другое", "Other", True, False, 6),
]

CRAVING_TRIGGERS = [
    ("stress", "Стресс", "Stress", 0),
    ("boredom", "Скука", "Boredom", 1),
    ("after_meal", "После еды", "After a meal", 2),
    ("alcohol", "Алкоголь рядом", "Alcohol around", 3),
    ("social", "Компания", "Social setting", 4),
    ("commute", "Дорога", "Commute", 5),
    ("evening", "Вечер дома", "Evening at home", 6),
    ("tiredness", "Усталость", "Tiredness", 7),
    ("other", "Другое", "Other", 8),
]

HEALTH_TIMELINE = [
    ("smoking", 0, "Решение принято", "Decision made", "Отсчёт начинается сейчас.", ""),
    ("smoking", 8, "Угарный газ в норме", "Carbon monoxide normalises",
     "Уровень кислорода в крови возвращается к норме.", ""),
    ("smoking", 48, "Возвращаются вкус и запах", "Taste and smell return", "", ""),
    ("smoking", 72, "Дышать легче", "Breathing easier",
     "Бронхи расслабляются, объём лёгких растёт.", ""),
    ("smoking", 336, "Выносливость выше", "Endurance improves",
     "Кровообращение улучшается — это заметно в зале.", ""),
    ("smoking", 2160, "Кашель отступает", "Cough subsides", "", ""),
    ("sugar", 0, "Решение принято", "Decision made", "", ""),
    ("sugar", 72, "Меньше скачков энергии", "Fewer energy crashes", "", ""),
    ("sugar", 336, "Тяга слабеет", "Cravings fade",
     "Вкусовые рецепторы адаптируются, фрукты кажутся слаще.", ""),
    ("sugar", 720, "Ровнее вес и сон", "Steadier weight and sleep", "", ""),
    ("alcohol", 0, "Решение принято", "Decision made", "", ""),
    ("alcohol", 72, "Сон глубже", "Deeper sleep",
     "Алкоголь подавляет фазу быстрого сна — она возвращается.", ""),
    ("alcohol", 168, "Восстановление после тренировок быстрее", "Faster recovery", "", ""),
    ("alcohol", 720, "Печёночные показатели улучшаются", "Liver markers improve", "", ""),
]

# (name, load_type, equipment, unilateral, rest, [(muscle, role)], [movement_tags])
EXERCISES = [
    # грудь
    ("Жим штанги лёжа", "weight_reps", "barbell", False, 150,
     [("chest_pec", "primary"), ("triceps", "secondary"), ("delts_front", "secondary")],
     ["horizontal_push"]),
    ("Жим гантелей лёжа", "weight_reps", "dumbbell", True, 120,
     [("chest_pec", "primary"), ("triceps", "secondary")], ["horizontal_push"]),
    ("Жим в тренажёре на грудь", "weight_reps", "machine", False, 120,
     [("chest_pec", "primary"), ("triceps", "secondary")], ["horizontal_push"]),
    ("Жим гантелей на наклонной", "weight_reps", "dumbbell", True, 120,
     [("chest_pec", "primary"), ("delts_front", "secondary")], ["horizontal_push"]),
    ("Разведения гантелей лёжа", "weight_reps", "dumbbell", True, 90,
     [("chest_pec", "primary")], ["horizontal_push"]),
    ("Сведения в кроссовере", "weight_reps", "cable", False, 90,
     [("chest_pec", "primary")], ["horizontal_push"]),
    ("Отжимания от пола", "bodyweight_reps", "bodyweight", False, 90,
     [("chest_pec", "primary"), ("triceps", "secondary")], ["horizontal_push"]),
    ("Отжимания на брусьях", "bodyweight_reps", "bodyweight", False, 120,
     [("chest_pec", "primary"), ("triceps", "primary")], ["horizontal_push"]),
    # спина
    ("Подтягивания", "bodyweight_reps", "bodyweight", False, 150,
     [("back_lats", "primary"), ("biceps", "secondary")], ["vertical_pull"]),
    ("Тяга верхнего блока", "weight_reps", "cable", False, 120,
     [("back_lats", "primary"), ("biceps", "secondary")], ["vertical_pull"]),
    ("Тяга горизонтального блока", "weight_reps", "cable", False, 120,
     [("back_lats", "primary"), ("back_rhomboids", "secondary")], ["horizontal_pull"]),
    ("Тяга штанги в наклоне", "weight_reps", "barbell", False, 150,
     [("back_lats", "primary"), ("back_erectors", "secondary")],
     ["horizontal_pull", "hip_hinge"]),
    ("Тяга гантели в наклоне", "weight_reps", "dumbbell", True, 120,
     [("back_lats", "primary")], ["horizontal_pull"]),
    ("Тяга в тренажёре сидя", "weight_reps", "machine", False, 120,
     [("back_lats", "primary"), ("back_rhomboids", "secondary")], ["horizontal_pull"]),
    ("Пуловер на блоке", "weight_reps", "cable", False, 90,
     [("back_lats", "primary")], ["overhead"]),
    ("Шраги с гантелями", "weight_reps", "dumbbell", True, 90,
     [("back_traps", "primary")], ["horizontal_pull"]),
    ("Становая тяга", "weight_reps", "barbell", False, 210,
     [("back_erectors", "primary"), ("glutes", "primary"), ("hamstrings", "primary")],
     ["hip_hinge", "spinal_load"]),
    ("Гиперэкстензия", "bodyweight_reps", "bodyweight", False, 90,
     [("back_erectors", "primary"), ("glutes", "secondary")], ["hip_hinge"]),
    # плечи
    ("Жим штанги стоя", "weight_reps", "barbell", False, 150,
     [("delts_front", "primary"), ("triceps", "secondary")],
     ["overhead", "vertical_push", "spinal_load"]),
    ("Жим гантелей сидя", "weight_reps", "dumbbell", True, 120,
     [("delts_front", "primary"), ("delts_side", "secondary")],
     ["overhead", "vertical_push"]),
    ("Махи гантелями в стороны", "weight_reps", "dumbbell", True, 60,
     [("delts_side", "primary")], ["overhead"]),
    ("Махи в наклоне", "weight_reps", "dumbbell", True, 60,
     [("delts_rear", "primary")], ["horizontal_pull"]),
    ("Разведения в тренажёре назад", "weight_reps", "machine", False, 60,
     [("delts_rear", "primary"), ("back_rhomboids", "secondary")], ["horizontal_pull"]),
    # руки
    ("Подъём штанги на бицепс", "weight_reps", "barbell", False, 90,
     [("biceps", "primary")], ["elbow_flexion"]),
    ("Молотки с гантелями", "weight_reps", "dumbbell", True, 60,
     [("brachialis", "primary"), ("biceps", "primary")], ["elbow_flexion"]),
    ("Сгибания на бицепс на блоке", "weight_reps", "cable", False, 60,
     [("biceps", "primary")], ["elbow_flexion"]),
    ("Французский жим", "weight_reps", "barbell", False, 90,
     [("triceps", "primary")], ["overhead", "elbow_flexion"]),
    ("Разгибания на блоке", "weight_reps", "cable", False, 60,
     [("triceps", "primary")], ["elbow_flexion"]),
    ("Разгибание руки из-за головы", "weight_reps", "dumbbell", True, 60,
     [("triceps", "primary")], ["overhead", "elbow_flexion"]),
    # ноги
    ("Приседания со штангой", "weight_reps", "barbell", False, 210,
     [("quads", "primary"), ("glutes", "primary")], ["knee_dominant", "spinal_load"]),
    ("Жим ногами", "weight_reps", "machine", False, 150,
     [("quads", "primary"), ("glutes", "secondary")], ["knee_dominant"]),
    ("Разгибания ног в тренажёре", "weight_reps", "machine", False, 90,
     [("quads", "primary")], ["knee_dominant"]),
    ("Сгибания ног лёжа", "weight_reps", "machine", False, 90,
     [("hamstrings", "primary")], ["knee_dominant"]),
    ("Румынская тяга", "weight_reps", "barbell", False, 150,
     [("hamstrings", "primary"), ("glutes", "primary")], ["hip_hinge", "spinal_load"]),
    ("Выпады с гантелями", "weight_reps", "dumbbell", True, 120,
     [("quads", "primary"), ("glutes", "primary")], ["knee_dominant"]),
    ("Подъёмы на носки", "weight_reps", "machine", False, 60,
     [("calves", "primary")], ["knee_dominant"]),
    # кор
    ("Планка", "time", "bodyweight", False, 60, [("abs", "primary")], []),
    ("Боковая планка", "time", "bodyweight", True, 60,
     [("obliques", "primary")], []),
    ("Скручивания на блоке", "weight_reps", "cable", False, 60,
     [("abs", "primary")], ["spinal_flexion"]),
    ("Скручивания в тренажёре", "weight_reps", "machine", False, 60,
     [("abs", "primary")], ["spinal_flexion"]),
    ("Подъём ног в висе", "bodyweight_reps", "bodyweight", False, 90,
     [("abs", "primary")], ["spinal_flexion"]),
    ("Вис на перекладине", "time", "bodyweight", False, 60,
     [("forearms", "primary")], ["vertical_pull"]),
    ("Русский твист", "weight_reps", "dumbbell", False, 60,
     [("obliques", "primary")], ["rotation", "spinal_flexion"]),
    # кардио
    ("Бег", "distance", "bodyweight", False, 0, [("quads", "primary")], ["impact"]),
    ("Ходьба", "distance", "bodyweight", False, 0, [("quads", "secondary")], []),
    ("Велотренажёр", "distance", "machine", False, 0, [("quads", "primary")], []),
    ("Гребной тренажёр", "distance", "machine", False, 0,
     [("back_lats", "primary"), ("quads", "secondary")], ["horizontal_pull"]),
]

# Альтернативы «тренажёр занят» — задаются заранее.
ALTERNATIVES = [
    ("Жим в тренажёре на грудь", ["Жим гантелей лёжа", "Отжимания от пола", "Сведения в кроссовере"]),
    ("Жим штанги лёжа", ["Жим гантелей лёжа", "Жим в тренажёре на грудь"]),
    ("Тяга верхнего блока", ["Подтягивания", "Тяга в тренажёре сидя"]),
    ("Тяга горизонтального блока", ["Тяга гантели в наклоне", "Тяга в тренажёре сидя"]),
    ("Жим ногами", ["Приседания со штангой", "Выпады с гантелями"]),
    ("Разгибания ног в тренажёре", ["Выпады с гантелями"]),
    ("Жим гантелей сидя", ["Махи гантелями в стороны"]),
    ("Скручивания на блоке", ["Скручивания в тренажёре", "Подъём ног в висе"]),
]

# (name, serving_label, grams, protein, kcal, quick)
FOODS = [
    ("Творог 5%, 100 г", "100 г", 100, 16.0, 121, True),
    ("Творог 2%, 200 г пачка", "пачка", 200, 36.0, 206, True),
    ("Куриная грудка, 100 г", "100 г", 100, 31.0, 165, True),
    ("Протеиновый коктейль, мерная ложка", "порция", 30, 24.0, 120, True),
    ("Яйцо куриное", "штука", 60, 6.3, 78, True),
    ("Греческий йогурт, 150 г", "банка", 150, 15.0, 90, True),
    ("Индейка, 100 г", "100 г", 100, 29.0, 135, False),
    ("Лосось, 100 г", "100 г", 100, 20.0, 208, False),
    ("Тунец консервированный, банка", "банка", 150, 35.0, 160, False),
    ("Говядина постная, 100 г", "100 г", 100, 26.0, 187, False),
    ("Молоко 2,5%, стакан", "стакан", 250, 7.0, 130, False),
    ("Кефир 1%, стакан", "стакан", 250, 7.5, 100, False),
    ("Сыр твёрдый, 30 г", "30 г", 30, 7.5, 110, False),
    ("Овсянка сухая, 50 г", "50 г", 50, 6.0, 190, False),
    ("Гречка сухая, 70 г", "70 г", 70, 8.8, 240, False),
    ("Рис сухой, 70 г", "70 г", 70, 5.0, 250, False),
    ("Хлеб цельнозерновой, ломоть", "ломоть", 35, 3.0, 85, False),
    ("Банан", "штука", 120, 1.3, 105, False),
    ("Яблоко", "штука", 180, 0.5, 95, False),
    ("Орехи грецкие, 30 г", "30 г", 30, 4.5, 196, False),
    ("Арахисовая паста, ложка", "ложка", 20, 5.0, 120, False),
    ("Нут варёный, 100 г", "100 г", 100, 9.0, 164, False),
    ("Тофу, 100 г", "100 г", 100, 12.0, 120, False),
    ("Протеиновый батончик", "штука", 60, 20.0, 210, False),
    ("Скир, 150 г", "банка", 150, 17.0, 95, False),
]
