# Generated by Django 5.2.17 on 2026-09-18 20:29

import apps.reports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("week_start", models.DateField(db_index=True)),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("coach", "подробная, для тренера"),
                            ("self", "короткая, для себя"),
                        ],
                        default="self",
                        max_length=6,
                    ),
                ),
                (
                    "blocks_config",
                    models.JSONField(default=apps.reports.models.default_blocks_config),
                ),
                (
                    "stats",
                    models.JSONField(
                        default=dict,
                        help_text="Снапшот цифр: отчёт не меняется задним числом.",
                    ),
                ),
                ("headline_metric", models.CharField(blank=True, max_length=120)),
                ("verdict", models.CharField(blank=True, max_length=200)),
                ("weak_link", models.CharField(blank=True, max_length=200)),
                ("focus_next_week", models.CharField(blank=True, max_length=200)),
                ("pdf", models.FileField(blank=True, null=True, upload_to="reports/")),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "share_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.sharelink",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "week_start", "variant"),
                        name="weekly_report_uniq",
                    )
                ],
            },
        ),
    ]
