# Generated by Django 5.2.17 on 2026-09-18 20:29

import apps.body.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyCompositionScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("at", models.DateTimeField(db_index=True)),
                ("device", models.CharField(default="InBody", max_length=40)),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "body_fat_pct",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "body_fat_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "skeletal_muscle_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "total_water_l",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "intracellular_water_l",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "extracellular_water_l",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "protein_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "minerals_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "visceral_fat_level",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("bmr_kcal", models.PositiveIntegerField(blank=True, null=True)),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="scans/")),
                ("conditions_note", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="PhotoSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("interval_days", models.PositiveSmallIntegerField(default=14)),
                ("next_due_on", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProgressPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "pose",
                    models.CharField(
                        choices=[
                            ("front", "спереди"),
                            ("side", "сбоку"),
                            ("back", "сзади"),
                        ],
                        default="front",
                        max_length=6,
                    ),
                ),
                ("photo", models.ImageField(upload_to="progress/")),
                ("outline_used", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="BodyCompositionSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("arm_l", "рука левая"),
                            ("arm_r", "рука правая"),
                            ("trunk", "туловище"),
                            ("leg_l", "нога левая"),
                            ("leg_r", "нога правая"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "lean_mass_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "fat_mass_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "lean_pct_of_norm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="body.bodycompositionscan",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scan", "segment"), name="scan_segment_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BodyMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "site",
                    models.CharField(
                        choices=[
                            ("waist", "талия"),
                            ("chest", "грудь"),
                            ("hips", "бёдра"),
                            ("arm_l", "рука левая"),
                            ("arm_r", "рука правая"),
                            ("thigh_l", "бедро левое"),
                            ("thigh_r", "бедро правое"),
                            ("neck", "шея"),
                            ("calf", "икра"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value_cm", models.DecimalField(decimal_places=1, max_digits=5)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date", "site"), name="body_measurement_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeightEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("client_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("at", models.DateTimeField(db_index=True)),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "conditions",
                    models.JSONField(
                        blank=True, default=apps.body.models.default_conditions
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "вручную"),
                            ("scale", "умные весы"),
                            ("healthkit", "Apple Health"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "at"], name="body_weight_user_id_a56a15_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "client_id"),
                        name="body_weightentry_client_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeightTrendPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "raw_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("trend_kg", models.DecimalField(decimal_places=3, max_digits=6)),
                ("points_used", models.PositiveSmallIntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"), name="weight_trend_uniq"
                    )
                ],
            },
        ),
    ]
