# Generated by Django 5.2.17 on 2026-09-18 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("serving_label", models.CharField(default="порция", max_length=40)),
                ("serving_grams", models.PositiveIntegerField(blank=True, null=True)),
                ("protein_g", models.DecimalField(decimal_places=1, max_digits=6)),
                ("calories", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "fat_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "carbs_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "sugar_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                ("barcode", models.CharField(blank=True, db_index=True, max_length=32)),
                ("is_quick_button", models.BooleanField(default=False)),
                ("use_count", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_quick_button", "-use_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="FreeMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("planned_for", models.DateField()),
                ("happened_on", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("within_limit", models.BooleanField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-planned_for"],
            },
        ),
        migrations.CreateModel(
            name="MealEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("client_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("at", models.DateTimeField(db_index=True)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "завтрак"),
                            ("lunch", "обед"),
                            ("dinner", "ужин"),
                            ("snack", "перекус"),
                        ],
                        default="snack",
                        max_length=12,
                    ),
                ),
                (
                    "protein_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=7),
                ),
                ("calories", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "fat_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "carbs_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="meals/")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("quick", "быстрая кнопка"),
                            ("template", "шаблон"),
                            ("barcode", "штрихкод"),
                            ("manual", "вручную"),
                            ("photo_only", "только фото"),
                        ],
                        default="quick",
                        max_length=12,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MealEntryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_name", models.CharField(blank=True, max_length=120)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=6),
                ),
                (
                    "protein_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "food_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="nutrition.fooditem",
                    ),
                ),
                (
                    "meal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="nutrition.mealentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MealTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=80)),
                ("default_meal_type", models.CharField(blank=True, max_length=12)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MealTemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=6),
                ),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="nutrition.fooditem",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="nutrition.mealtemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=80)),
                ("default_time", models.TimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SupplementLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("client_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("date", models.DateField(db_index=True)),
                ("taken", models.BooleanField(default=True)),
                (
                    "supplement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="nutrition.supplement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WaterLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("client_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("at", models.DateTimeField(db_index=True)),
                ("volume_ml", models.PositiveIntegerField(default=250)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DietExceptionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("client_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("at", models.DateTimeField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("sweets", "сладкое"),
                            ("fastfood", "фастфуд"),
                            ("alcohol", "алкоголь"),
                            ("sugary_drink", "сладкие напитки"),
                            ("other", "другое"),
                        ],
                        max_length=14,
                    ),
                ),
                ("amount_note", models.CharField(blank=True, max_length=120)),
                (
                    "estimated_sugar_g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "client_id"),
                        name="nutrition_dietexceptionlog_client_uniq",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="fooditem",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="food_owner_name_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="mealentry",
            constraint=models.UniqueConstraint(
                fields=("user", "client_id"), name="nutrition_mealentry_client_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplementlog",
            constraint=models.UniqueConstraint(
                fields=("user", "client_id"), name="nutrition_supplementlog_client_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplementlog",
            constraint=models.UniqueConstraint(
                fields=("supplement", "date"), name="supplement_log_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="waterlog",
            constraint=models.UniqueConstraint(
                fields=("user", "client_id"), name="nutrition_waterlog_client_uniq"
            ),
        ),
    ]
