# Generated by Django 5.2.17 on 2026-09-18 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationsettings",
            name="morning_weigh_in_time",
            field=models.TimeField(default=datetime.time(8, 30)),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="quiet_hours_from",
            field=models.TimeField(default=datetime.time(23, 0)),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="quiet_hours_to",
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
